### ISSUE TITLE
'KEY_LEFT_ESC' was not declared in this scope

### ISSUE THREAD

**Issue by PieJohnson** [Nurrl/Dckuino.js#20] opened 2017-03-21 22:07 UTC
The Arduino ide gives me the error "'KEY_LEFT_ESC' was not declared in this scope" when I try to verify the code.  Can someone tell me what the cause of this issue is?

**Comment by Nurrl** [comment] 2017-03-22 06:00
Just rebuild the code with Dckuino.js, this is a duplicate of #18 and has been fixed by #19 :D (The fix was to replace **KEY_LEFT_ESC** by **KEY_ESC**)
Thanks anyway for the report ^^

**Closed** 2017-03-22 06:00 UTC
Labels: duplicate, fixed
